import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Header from "@/components/Header/Header";
import classNames from "classnames/bind";
import styles from "@/styles/AppLayout.module.scss";
import Footer from "@/components/Footer/Footer";
import 'react-tippy/dist/tippy.css'

import ReduxProvider from "@/redux/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "", // Dùng ở router con nếu muốn ghi đẻ template
    default: "Kusakari",
    template: "", // e.g "%s | Kusakari" if childrent has title it will be Blog | Kusakari
  },
  description: "Generated by create next app",
};
const cx = classNames.bind(styles);




export default function RootLayout({
  children,
  friends,
  settings,
  notify,
}: {
  children: React.ReactNode;
  friends: React.ReactNode;
  settings: React.ReactNode;
  notify : React.ReactNode;
  
}) {
  
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />

          <div className={cx("body")}>
            <div className={cx("left_main")}>{friends}</div>
            <div className={cx("middle_main")}>{children}</div>
            <div className={cx("right_main")}>{settings}</div>
          </div>

          <Footer />
        </body>
      </html>
    </ReduxProvider>
  );
}
